USER_CREATED = "USER_CREATED"
ADMIN_CREATED = "ADMIN_CREATED"

LOGIN_SUCCESS = "LOGIN_SUCCESS"
LOGIN_FAILED = "LOGIN_FAILED"

ROLE_CHANGED = "ROLE_CHANGED"

USER_SUSPENDED = "USER_SUSPENDED"
USER_ACTIVATED = "USER_ACTIVATED"

API_KEY_REVOKED = "API_KEY_REVOKED"
API_KEY_REGENERATED = "API_KEY_REGENERATED"

QUOTA_EXCEEDED = "QUOTA_EXCEEDED"

DOCUMENT_ACCESS_DENIED = "DOCUMENT_ACCESS_DENIED"

TENANT_CREATED = "TENANT_CREATED"
TENANT_UPDATED = "TENANT_UPDATED"