"""add_clause_analyses_table

Revision ID: 06030a7d75f0
Revises: 2e8baf7f2779
Create Date: 2026-05-01 13:07:39.507221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06030a7d75f0'
down_revision: Union[str, None] = '2e8baf7f2779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clause_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('clause_type', sa.String(), nullable=False),
    sa.Column('matched_text', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clause_analyses_chunk_id'), 'clause_analyses', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_clause_analyses_clause_type'), 'clause_analyses', ['clause_type'], unique=False)
    op.create_index(op.f('ix_clause_analyses_document_id'), 'clause_analyses', ['document_id'], unique=False)
    op.create_index(op.f('ix_clause_analyses_id'), 'clause_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clause_analyses_id'), table_name='clause_analyses')
    op.drop_index(op.f('ix_clause_analyses_document_id'), table_name='clause_analyses')
    op.drop_index(op.f('ix_clause_analyses_clause_type'), table_name='clause_analyses')
    op.drop_index(op.f('ix_clause_analyses_chunk_id'), table_name='clause_analyses')
    op.drop_table('clause_analyses')
    # ### end Alembic commands ###
