"""add_chunk_text_to_embeddings

Revision ID: b2854419a025
Revises: 06030a7d75f0
Create Date: 2026-05-01 13:25:24.195874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2854419a025'
down_revision: Union[str, None] = '06030a7d75f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('chunk_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embeddings', 'chunk_text')
    # ### end Alembic commands ###
