CLAUSE_PATTERNS = {
    "termination": [
        r"\bterminate\b",
        r"\btermination\b",
        r"\bcancel\b",
        r"\bbreach\b",
    ],
    "liability": [
        r"\bliability\b",
        r"\blimit of liability\b",
        r"\bdamages\b",
        r"\bconsequential damages\b",
    ],
    "indemnification": [
        r"\bindemnify\b",
        r"\bindemnification\b",
        r"\bhold harmless\b",
    ],
    "confidentiality": [
        r"\bconfidential\b",
        r"\bnon-disclosure\b",
        r"\bnda\b",
        r"\bproprietary information\b",
    ],
    "compliance": [
        r"\bcompliance\b",
        r"\bregulation\b",
        r"\blaw\b",
        r"\bgdpr\b",
        r"\bhipaa\b",
    ],
    "payment": [
        r"\bpayment\b",
        r"\bfees\b",
        r"\binvoice\b",
        r"\bbilling\b",
        r"\bdue date\b",
    ],
    "refunds": [
        r"\brefund\b",
        r"\breturns?\b",
        r"\breimbursement\b",
    ],
    "warranty": [
        r"\bwarranty\b",
        r"\bguarantee\b",
        r"\bmerchantability\b",
        r"\bas is\b",
    ],
    "governing_law": [
        r"\bgoverning law\b",
        r"\bjurisdiction\b",
        r"\bvenue\b",
        r"\bapplicable law\b",
    ],
    "dispute_resolution": [
        r"\barbitration\b",
        r"\bdispute\b",
        r"\bmediation\b",
        r"\blitigation\b",
    ],
    "force_majeure": [
        r"\bforce majeure\b",
        r"\bact of god\b",
        r"\bunforeseen circumstances\b",
    ],
    "data_privacy": [
        r"\bdata privacy\b",
        r"\bdata protection\b",
        r"\bpersonal data\b",
        r"\bprivacy policy\b",
    ],
    "service_levels": [
        r"\bservice level\b",
        r"\buptime\b",
        r"\bavailability\b",
        r"\bperformance standards\b",
    ],
    "intellectual_property": [
        r"\bintellectual property\b",
        r"\bip ownership\b",
        r"\bcopyright\b",
        r"\btrademark\b",
        r"\blicense\b",
    ],
}